apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: env59-node-alias
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  spiffeID: spiffe://stack.ai/cluster/env59/node
  parentID: spiffe://stack.ai/spire/server
  selectors:
    - azure_imds:subscription-id:c05b8dd7-5b0f-4be7-ba37-5f5a0eb52ca8
    - azure_imds:resource-group:mc_stackai-env59-rg_env59-aks_eastus
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: env59-argocd-agent-agent
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  spiffeID: spiffe://stack.ai/cluster/env59/ns/stackai-addons/sa/argocd-agent-agent
  parentID: spiffe://stack.ai/cluster/env59/node
  selectors:
    - k8s:ns:stackai-addons
    - k8s:sa:argocd-agent-agent
