data "azurerm_resource_group" "spoke" {
  name = var.resource_group_name
}

resource "azurerm_key_vault" "main" {
  name                       = substr(replace("${var.environment}-stackai-kv", "_", "-"), 0, 24)
  resource_group_name        = data.azurerm_resource_group.spoke.name
  location                   = data.azurerm_resource_group.spoke.location
  tenant_id                  = var.tenant_id
  sku_name                   = "standard"
  enable_rbac_authorization  = true
  purge_protection_enabled   = true
  soft_delete_retention_days = 30

  public_network_access_enabled = true
  network_acls {
    bypass         = "AzureServices"
    default_action = "Allow"
  }
}

resource "random_bytes" "supabase_cookie_secret" {
  length = 24
}

resource "azurerm_key_vault_secret" "supabase_oauth" {
  name         = "${var.environment}-supabase-oauth"
  key_vault_id = azurerm_key_vault.main.id
  value = jsonencode({
    cookie_secret = random_bytes.supabase_cookie_secret.base64
  })

  lifecycle {
    ignore_changes = [value]
  }
}

resource "incident_alert_source" "monitoring" {
  name            = "${var.environment}-monitoring"
  source_type     = "http"
  owning_team_ids = ["01KPP55R5BDGP5X40A5531YR3G"]

  template = {
    expressions = []
    title = {
      literal = jsonencode({
        type = "doc"
        content = [{
          type = "paragraph"
          content = [{
            type = "varSpec"
            attrs = {
              name    = "title"
              label   = "Payload → Title"
              missing = false
            }
          }]
        }]
      })
    }
    description = {
      literal = jsonencode({
        type = "doc"
        content = [{
          type = "paragraph"
          content = [{
            type = "varSpec"
            attrs = {
              name    = "description"
              label   = "Payload → Description"
              missing = false
            }
          }]
        }]
      })
    }
    attributes = []
  }
}

resource "incident_alert_route" "monitoring" {
  name       = "${var.environment}-alert"
  enabled    = true
  is_private = false

  alert_sources = [{
    alert_source_id  = incident_alert_source.monitoring.id
    condition_groups = []
  }]

  condition_groups = []
  expressions      = []
  owning_team_ids  = ["01KPP55R5BDGP5X40A5531YR3G"]

  channel_config = [{
    condition_groups = []
    slack_targets = {
      binding = {
        value = {
          literal = "T03V7MR4L9Y/C0ASA7NMRUZ"
        }
      }
      channel_visibility = "private"
    }
  }]

  escalation_config = {
    auto_cancel_escalations = true
    escalation_targets = [{
      escalation_paths = {
        array_value = [{
          literal = "01KS1VMFN5W6DSHFP744VVPPRX"
        }]
      }
    }]
  }

  incident_config = {
    enabled                 = false
    auto_decline_enabled    = false
    condition_groups        = []
    defer_time_seconds      = 300
    grouping_window_seconds = 300
    grouping_keys           = []
  }

  incident_template = {
    name          = { autogenerated = true }
    summary       = { autogenerated = true }
    custom_fields = []
  }
}

resource "azurerm_key_vault_secret" "monitoring" {
  name         = "${var.environment}-monitoring-secrets"
  key_vault_id = azurerm_key_vault.main.id
  value = jsonencode({
    INCIDENT_ALERT_URL    = incident_alert_source.monitoring.alert_events_url
    INCIDENT_BEARER_TOKEN = incident_alert_source.monitoring.secret_token
  })

  lifecycle {
    ignore_changes = [value]
  }
}

resource "azurerm_key_vault_secret" "customer_secrets" {
  name         = "${var.environment}-customer-secrets"
  key_vault_id = azurerm_key_vault.main.id
  value        = jsonencode(var.customer_secrets)

  lifecycle {
    ignore_changes = [value]
  }

}

resource "random_password" "temporal_db" {
  count   = var.apps_temporal ? 1 : 0
  length  = 32
  special = false
}

resource "azurerm_key_vault_secret" "temporal_secrets" {
  count = var.apps_temporal ? 1 : 0

  name         = "${var.environment}-temporal-secrets"
  key_vault_id = azurerm_key_vault.main.id
  value = jsonencode({
    db_password = random_password.temporal_db[0].result
  })

  lifecycle {
    ignore_changes = [value]
  }

}

resource "azurerm_key_vault_secret" "acr_credentials" {
  name         = "${var.environment}-acr-credentials"
  key_vault_id = azurerm_key_vault.main.id
  value = jsonencode({
    server   = var.acr_credentials.server
    username = var.acr_credentials.username
    password = var.acr_credentials.password
  })

  lifecycle {
    ignore_changes = [value]
  }

}
