{{- range $name, $cfg := .Values.namespaces }}
{{- if $cfg.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  {{- if or $cfg.ambient $cfg.acrPull }}
  labels:
    {{- if $cfg.ambient }}
    istio.io/dataplane-mode: ambient
    {{- end }}
    {{- if $cfg.acrPull }}
    stackai.com/acr-pull: "true"
    {{- end }}
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
{{- end }}
{{- end }}
