{{- if .Values.externalSecrets.unstructured.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unstructured-external-secret
  namespace: unstructured
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: unstructured-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        DEBUG: "false"
        ENVIRONMENT: "production"
        LOG_LEVEL: "INFO"
        UNSTRUCTURED_PARALLEL_MODE_ENABLED: "false"
        UNSTRUCTURED_PARALLEL_MODE_RETRY_ATTEMPTS: "2"
        UNSTRUCTURED_PARALLEL_MODE_SPLIT_SIZE: "1"
        UNSTRUCTURED_PARALLEL_MODE_THREADS: "3"
        UNSTRUCTURED_API_KEY: "{{`{{ .unstructured_api_key }}`}}"
  data:
    - secretKey: unstructured_api_key
      remoteRef:
        key: {{ .Values.env }}-unstructured-secrets
        property: unstructured_api_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
