{{- if .Values.externalSecrets.stackweb.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stackweb-external-secret
  namespace: stackweb
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: stackweb-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        ENVIRONMENT: "production"
        ON_PREMISE: "true"
        NEXT_PUBLIC_VERCEL_ENV: "production"
        NEXT_PUBLIC_URL: "https://{{ .Values.domain }}"
        NEXT_PUBLIC_STACKEND_URL: "https://api.{{ .Values.domain }}/"
        NEXT_PUBLIC_SUPABASE_URL: "https://supabase.{{ .Values.domain }}"
        NEXT_PUBLIC_LEADERBOARD_API_URL: "http://llm-leaderboard.llm-leaderboard.svc.cluster.local:8000"
        SUPABASE_SERVICE_ROLE_KEY: "{{`{{ .supabase_service_role_key }}`}}"
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "{{`{{ .supabase_anon_key }}`}}"
        NEXT_PUBLIC_CHAT_WITH_FLOW_PROJECT_ID: "69cd6273a9d93f1000ccf32f"
        NEXT_PUBLIC_CHAT_WITH_FLOW_PUBLIC_API_KEY_UUID: "2ee16279-c487-48ef-a094-f38682378f66"
  data:
    - secretKey: supabase_service_role_key
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: service_role_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: supabase_anon_key
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: anon_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  dataFrom:
    - extract:
        key: {{ .Values.env }}-customer-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
