{{- if .Values.externalSecrets.weaviate.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weaviate-api-key-external-secret
  namespace: weaviate
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: weaviate-api-key
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  data:
    - secretKey: AUTHENTICATION_APIKEY_ALLOWED_KEYS
      remoteRef:
        key: {{ .Values.env }}-weaviate-secrets
        property: weaviate_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
