{{- if .Values.externalSecrets.supabase.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-saml-secrets-external-secret
  namespace: supabase
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: supabase-saml-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        GOTRUE_SAML_PRIVATE_KEY: "{{`{{ .saml_private_key }}`}}"
  dataFrom:
    - extract:
        key: {{ .Values.env }}-supabase-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-db-external-secret
  namespace: supabase
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: supabase-db-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        password: "{{`{{ .password }}`}}"
        password_encoded: "{{`{{ .password | urlquery }}`}}"
        database: "postgres"
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: db_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-secrets-external-secret
  namespace: supabase
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: supabase-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        DB_ENC_KEY: "{{`{{ .encryption_key }}`}}"
  dataFrom:
    - extract:
        key: {{ .Values.env }}-supabase-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-google-oauth-external-secret
  namespace: supabase
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: supabase-google-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        cookie-secret: "{{`{{ .cookie_secret }}`}}"
  dataFrom:
    - extract:
        key: {{ .Values.env }}-supabase-oauth
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-init-external-secret
  namespace: supabase
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: supabase-init-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin_email
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: admin_email
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: admin_password
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: admin_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: org_id
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: org_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: org_name
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: org_name
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-s3-external-secret
  namespace: supabase
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: supabase-s3
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        accessKeyId: "supa-storage"
        secretAccessKey: "{{`{{ .minio_secret_key }}`}}"
        accessKey: "{{`{{ .minio_secret_key }}`}}"
        keyId: "supa-storage"
  data:
    - secretKey: minio_secret_key
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: minio_secret_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
