{{- if .Values.externalSecrets.stackend.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stackend-external-secret
  namespace: stackend
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: stackend-app-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        ENVIRONMENT: "production"
        DEPLOYMENT_ENVIRONMENT: "production_stackend"
        TENANT_ID: {{ .Values.env | quote }}
        IS_CELERY_WORKER: "false"
        NUM_WORKERS: "1"
        CELERY_CONCURRENCY: "1"
        ALLOW_PARALLEL_FLOW_EXECUTION: "true"
        TEMPORAL_SELF_HOSTED: "True"
        TEMPORAL_TLS_ENABLED: "false"
        TEMPORAL_ADDRESS: "temporal-frontend.temporal.svc.cluster.local:7233"
        TEMPORAL_NAMESPACE: "parsing"
        TEMPORAL_API_KEY: "not-required-for-self-hosted"
        TEMPORAL_CLOUD: "false"
        STACKWEB_URL: "https://{{ .Values.domain }}"
        STACKEND_API_URL: "https://api.{{ .Values.domain }}"
        STACKEND_US_EAST_API_URL: "https://api.{{ .Values.domain }}"
        INDEXING_API_URL: "https://api.{{ .Values.domain }}"
        SUPABASE_URL: "https://supabase.{{ .Values.domain }}"
        CELERY_BACKEND_URL: "redis://stackend-valkey.stackend.svc.cluster.local:6379"
        CELERY_BROKER_URL: "redis://stackend-valkey.stackend.svc.cluster.local:6379"
        REDIS_URL: "redis://stackend-valkey.stackend.svc.cluster.local:6379"
        REDIS_US_EAST_URL: "redis://stackend-valkey.stackend.svc.cluster.local:6379"
        WEAVIATE_URL: "weaviate.weaviate.svc.cluster.local"
        WEAVIATE_HTTP_PORT: "9090"
        WEAVIATE_GRPC_PORT: "50051"
        SELF_HOSTED_WEAVIATE: "true"
        UNSTRUCTURED_URL: "http://unstructured.unstructured.svc.cluster.local:8000"
        REPL_URL: "http://stackrepl.stackrepl.svc.cluster.local:8000/execute_code/"
        NGROK_URL: ""
        POSTGRES_DB_HOST: "supabase-supabase-db.supabase.svc.cluster.local"
        POSTGRES_DB_PORT: "5432"
        POSTGRES_DB_NAME: "postgres"
        POSTGRES_DB_USER: "postgres"
        POSTGRES_DB_PASSWORD: "{{`{{ .db_password }}`}}"
        SUPABASE_JWT_SECRET: "{{`{{ .supabase_jwt_secret }}`}}"
        SUPABASE_ANON_KEY: "{{`{{ .supabase_anon_key }}`}}"
        SUPABASE_SERVICE_ROLE_KEY: "{{`{{ .supabase_service_role_key }}`}}"
        SUPABASE_ENCRYPTION_KEY: "{{`{{ .supabase_encryption_key }}`}}"
        MONGODB_URI: "mongodb://admin:{{`{{ .mongodb_admin_password | urlquery }}`}}@mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-2.mongodb-svc.mongodb.svc.cluster.local:27017/?replicaSet=mongodb&authSource=admin"
        WEAVIATE_KEY: "{{`{{ .weaviate_key }}`}}"
        UNSTRUCTURED_API_KEY: "{{`{{ .unstructured_api_key }}`}}"
        PARSER_SERVICE_ADMIN_TOKEN: "{{`{{ .parser_admin_token }}`}}"
        AWS_ACCESS_KEY_ID: 'supa-storage'
        AWS_SECRET_ACCESS_KEY: '{{`{{ .minio_secret_key }}`}}'
        AWS_DEFAULT_REGION: {{ .Values.aws.region | quote }}
        S3_AWS_ACCESS_KEY: 'supa-storage'
        S3_AWS_SECRET_ACCESS_KEY: '{{`{{ .minio_secret_key }}`}}'
        S3_AWS_REGION: {{ .Values.aws.region | quote }}
        S3_URL: 'http://supabase-supabase-storage.supabase.svc.cluster.local:5000/s3'
  data:
    - secretKey: db_password
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: db_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: supabase_jwt_secret
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: jwt_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: supabase_anon_key
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: anon_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: supabase_service_role_key
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: service_role_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: supabase_encryption_key
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: encryption_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: minio_secret_key
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: minio_secret_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: mongodb_admin_password
      remoteRef:
        key: {{ .Values.env }}-mongodb-secrets
        property: admin_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: weaviate_key
      remoteRef:
        key: {{ .Values.env }}-weaviate-secrets
        property: weaviate_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: unstructured_api_key
      remoteRef:
        key: {{ .Values.env }}-unstructured-secrets
        property: unstructured_api_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: parser_admin_token
      remoteRef:
        key: {{ .Values.env }}-parser-secrets
        property: admin_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  dataFrom:
    - extract:
        key: {{ .Values.env }}-customer-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-db-external-secret
  namespace: stackend
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: supabase-db-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        password: "{{`{{ .password }}`}}"
        password_encoded: "{{`{{ .password | urlquery }}`}}"
        database: "postgres"
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: db_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-init-external-secret
  namespace: stackend
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: supabase-init-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin_email
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: admin_email
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: admin_password
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: admin_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: org_id
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: org_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: org_name
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: org_name
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: dashboard_password
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: dashboard_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: username
      remoteRef:
        key: {{ .Values.env }}-supabase-secrets
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
