{{- range $name, $cfg := .Values.httpRoutes }}
{{- if $cfg.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $cfg.name | default $name }}
  namespace: {{ $cfg.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $cfg.gateway.name }}
      namespace: {{ $cfg.gateway.namespace | default "istio-system" }}
  hostnames:
    {{- range $cfg.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - matches:
        {{- range $cfg.paths }}
        - path:
            type: PathPrefix
            value: {{ . | quote }}
        {{- end }}
      backendRefs:
        - group: ''
          kind: Service
          name: {{ $cfg.backend.name }}
          port: {{ $cfg.backend.port }}
          weight: 1
{{- end }}
{{- end }}
