apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-kube-agent
  namespace: __ENV_NAME__
  labels:
    argocd.argoproj.io/agent-id: __ENV_NAME__
spec:
  project: default
  source:
    repoURL: https://charts.releases.teleport.dev
    chart: teleport-kube-agent
    targetRevision: 18.7.4
    helm:
      releaseName: teleport-kube-agent
      valuesObject:
        roles: "kube"
        proxyAddr: "teleport-agents.ops.stack.ai:443"
        teleportClusterName: "teleport.ops.stack.ai"
        joinParams:
          method: kubernetes
          tokenName: "__ENV_NAME__-agent-kube"
        kubeClusterName: "__ENV_NAME__"
        labels:
          env: __ENV_NAME__
        serviceAccount:
          create: true
          name: "teleport-kube-agent"
        highAvailability:
          replicaCount: 2
          podDisruptionBudget:
            enabled: true
            minAvailable: 1
        log:
          level: INFO
          format: json
          output: stderr
        enterprise: false
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 300m
            memory: 1Gi
  destination:
    name: __ENV_NAME__
    namespace: teleport
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
