apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: env61
  labels:
    argocd.argoproj.io/agent-id: env61
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    targetRevision: 0.17.0
    helm:
      releaseName: nvidia-device-plugin
      valuesObject:
        priorityClassName: system-node-critical
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        env:
          - name: FAIL_ON_INIT_ERROR
            value: "false"
  destination:
    name: env61
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
