---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-kube-agent
  namespace: stackai-addons
  labels:
    app: teleport-kube-agent
    environment: common
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
spec:
  project: default
  source:
    repoURL: https://charts.releases.teleport.dev
    targetRevision: 18.7.4
    chart: teleport-kube-agent
    helm:
      releaseName: teleport-kube-agent
      valuesObject:
        roles: "kube"
        proxyAddr: "teleport-agents.ops.stack.ai:443"
        authToken: "common-aks-agent-kube"
        joinParams:
          method: kubernetes
          tokenName: "common-aks-agent-kube"

        kubeClusterName: "common-aks"
        labels:
          env: common-aks

        serviceAccount:
          create: true
          name: "teleport-kube-agent"

        highAvailability:
          replicaCount: 2
          podDisruptionBudget:
            enabled: true
            minAvailable: 1

        log:
          level: INFO
          format: json
          output: stderr

        enterprise: false

        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 300m
            memory: 1Gi

  destination:
    namespace: teleport
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
