{{- if .Values.externalSecrets.acrPull.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: acr-pull
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  externalSecretName: acr-pull-external-secret
  namespaceSelectors:
    - matchLabels:
        stackai.com/acr-pull: "true"
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      name: {{ .Values.externalSecrets.store.name }}
      kind: ClusterSecretStore
    target:
      name: acr-pull-secret
      creationPolicy: Owner
      deletionPolicy: Retain
      template:
        type: kubernetes.io/dockerconfigjson
        engineVersion: v2
        data:
          .dockerconfigjson: |
            {"auths":{"{{ `{{ .server }}` }}":{"username":"{{ `{{ .username }}` }}","password":"{{ `{{ .password }}` }}","auth":"{{ `{{ printf "%s:%s" .username .password | b64enc }}` }}"}}}
    data:
      - secretKey: server
        remoteRef:
          key: {{ .Values.externalSecrets.acrPull.sourceSecret | quote }}
          property: server
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
      - secretKey: username
        remoteRef:
          key: {{ .Values.externalSecrets.acrPull.sourceSecret | quote }}
          property: username
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
      - secretKey: password
        remoteRef:
          key: {{ .Values.externalSecrets.acrPull.sourceSecret | quote }}
          property: password
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
{{- end }}
