{{- if .Values.externalSecrets.store.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.store.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-12"
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.externalSecrets.vaultUrl | quote }}
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
{{- end }}
