{{- if .Values.mongodbExternalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-external-secret
  namespace: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecrets.store.name }}
    kind: ClusterSecretStore
  target:
    name: mongodb-admin-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.mongodbExternalSecret.sourceSecret | quote }}
        property: admin_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
