# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "azurerm" {
  environment     = "public"
  tenant_id       = "562d3203-96d4-4a11-85af-5f4c197ce345"
  subscription_id = "c05b8dd7-5b0f-4be7-ba37-5f5a0eb52ca8"
  features {}
}
