apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: __ENV_NAME__
  labels:
    app: istiod
    argocd.argoproj.io/agent-id: __ENV_NAME__
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: "1.29.4"
      helm:
        releaseName: istiod
        valuesObject:
          autoscaleMin: 4
          replicaCount: 4
          profile: ambient
          global:
            logAsJson: true
          pilot:
            env:
              CA_TRUSTED_NODE_ACCOUNTS: "kube-system/ztunnel,istio-system/ztunnel"
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
          meshConfig:
            accessLogFile: "/dev/stdout"
            accessLogEncoding: "JSON"
            enableTracing: false
  destination:
    name: __ENV_NAME__
    namespace: istio-system
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[].namespaceSelector.matchExpressions[]? | select(.key == "control-plane" or .key == "kubernetes.azure.com/managedby")'
        - '.webhooks[].objectSelector.matchExpressions[]? | select(.key == "control-plane" or .key == "kubernetes.azure.com/managedby")'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].failurePolicy
        - '.webhooks[].namespaceSelector.matchExpressions[]? | select(.key == "control-plane" or .key == "kubernetes.azure.com/managedby")'
        - '.webhooks[].objectSelector.matchExpressions[]? | select(.key == "control-plane" or .key == "kubernetes.azure.com/managedby")'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
