apiVersion: resources.teleport.dev/v2
kind: TeleportProvisionToken
metadata:
  name: env63-agent-kube
  namespace: teleport
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  roles:
    - Kube
  join_method: kubernetes
  kubernetes:
    type: oidc
    oidc:
      issuer: "https://eastus.oic.prod-aks.azure.com/2a377f54-325c-469f-8fa6-944a91f7a2f5/4eb07895-e381-4342-9b4d-c12a9429ed86/"
    allow:
      - service_account: "teleport:teleport-kube-agent"
