apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: __ENV_NAME__
  labels:
    app: temporal
    environment: __ENV_NAME__
    argocd.argoproj.io/agent-id: __ENV_NAME__
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: temporal
    name: __ENV_NAME__
  project: default
  source:
    repoURL: stackai.azurecr.io
    chart: charts/temporal
    targetRevision: 0.1.0
    helm:
      releaseName: temporal
      valuesObject:
        postgresql:
          persistence:
            storageClass: managed-csi
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: temporal-postgresql
      namespace: temporal
      jqPathExpressions:
        - .spec.volumeClaimTemplates[].apiVersion
        - .spec.volumeClaimTemplates[].kind
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
