apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weaviate
  namespace: env63
  labels:
    app: weaviate
    environment: env63
    argocd.argoproj.io/agent-id: env63
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: weaviate
    name: env63
  project: default
  source:
    repoURL: stackai.azurecr.io
    chart: charts/weaviate
    targetRevision: 0.1.0
    helm:
      releaseName: weaviate
      valuesObject:
        image:
          registry: stackai.azurecr.io
          repo: weaviate
          tag: "1.29.0"
          pullSecrets:
            - acr-pull-secret
        replicas: 3
        authentication:
          anonymous_access:
            enabled: false
        env:
          AUTHENTICATION_APIKEY_ENABLED: "true"
          AUTHENTICATION_APIKEY_USERS: "admin@stack-ai.com"
        envSecrets:
          AUTHENTICATION_APIKEY_ALLOWED_KEYS: weaviate-api-key
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        storage:
          size: 50Gi
          storageClassName: managed-csi
        service:
          type: ClusterIP
          name: weaviate
          ports:
            - name: http
              protocol: TCP
              port: 9090
              targetPort: 8080
            - name: grpc
              protocol: TCP
              port: 50051
              targetPort: 50051
        grpcService:
          enabled: false
        ingress:
          enabled: false
        modules:
          text2vec-openai:
            enabled: false
          text2vec-cohere:
            enabled: false
          text2vec-huggingface:
            enabled: false
          generative-openai:
            enabled: false
        initContainers:
          sysctlInitContainer:
            enabled: true
            sysctlVmMaxMapCount: 524288
        annotations:
          reloader.stakater.com/auto: "true"
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: weaviate
      jsonPointers:
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind
        - /spec/volumeClaimTemplates/0/spec/volumeMode
        - /spec/volumeClaimTemplates/0/status
    - kind: Secret
      name: weaviate-cluster-api-basic-auth
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
