# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    resource_group_name  = "stackai-env59-rg"
    storage_account_name = "env59stackaitfstate"
    container_name       = "tfstate"
    key                  = "env59/08-apps/terraform.tfstate"
    use_azuread_auth     = true
    subscription_id      = "c05b8dd7-5b0f-4be7-ba37-5f5a0eb52ca8"
    tenant_id            = "562d3203-96d4-4a11-85af-5f4c197ce345"
  }
}
