apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-podinfo
  namespace: env60
  labels:
    argocd.argoproj.io/agent-id: env60
spec:
  project: default
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    targetRevision: 6.9.1
    helm:
      releaseName: test-podinfo
  destination:
    name: env60
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
