apiVersion: resources.teleport.dev/v2
kind: TeleportProvisionToken
metadata:
  name: env62-agent-kube
  namespace: teleport
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  roles:
    - Kube
  join_method: kubernetes
  kubernetes:
    type: oidc
    oidc:
      issuer: "https://eastus.oic.prod-aks.azure.com/562d3203-96d4-4a11-85af-5f4c197ce345/3b4e1d1f-c1e3-4ea8-b2cc-b5b8818cdb09/"
    allow:
      - service_account: "teleport:teleport-kube-agent"
