apiVersion: resources.teleport.dev/v2
kind: TeleportProvisionToken
metadata:
  name: env62-agent-kube
  namespace: teleport
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  roles:
    - Kube
  join_method: kubernetes
  kubernetes:
    type: oidc
    oidc:
      issuer: "https://eastus.oic.prod-aks.azure.com/562d3203-96d4-4a11-85af-5f4c197ce345/5d8c9266-2456-4115-b0d4-402a8aa802ef/"
    allow:
      - service_account: "teleport:teleport-kube-agent"
