apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: env62
  labels:
    argocd.argoproj.io/agent-id: env62
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.19.0
    helm:
      releaseName: external-dns
      valuesObject:
        provider:
          name: azure
        sources:
          - gateway-httproute
        policy: upsert-only
        txtOwnerId: env62
        domainFilters:
          - env62.stack.ai
        serviceAccount:
          create: false
          name: external-dns
        podLabels:
          azure.workload.identity/use: "true"
        secretConfiguration:
          enabled: true
          mountPath: /etc/kubernetes
          data:
            azure.json: |
              {
                "tenantId": "562d3203-96d4-4a11-85af-5f4c197ce345",
                "subscriptionId": "c05b8dd7-5b0f-4be7-ba37-5f5a0eb52ca8",
                "resourceGroup": "stackai-env62-rg",
                "useWorkloadIdentityExtension": true
              }
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
  destination:
    name: env62
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
