apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: env61
  labels:
    argocd.argoproj.io/agent-id: env61
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: 1.2.0
    helm:
      releaseName: reloader
      valuesObject:
        reloader:
          watchGlobally: true
          reloadOnCreate: true
          syncAfterRestart: true
          reloadStrategy: annotations
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
  destination:
    name: env61
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
