---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-external-secret
  namespace: tools-az
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: common-atlantis-azure-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  dataFrom:
    - extract:
        key: common-atlantis-azure-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
