apiVersion: v1
kind: Namespace
metadata:
  name: env61
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: env61-client-tls
  namespace: argocd
spec:
  secretName: env61-client-tls
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: env61
  usages:
    - client auth
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
---
apiVersion: v1
kind: Secret
metadata:
  name: env61-cluster
  namespace: argocd
  annotations:
    argoproj.io/skip-reconcile: "true"
  labels:
    argocd.argoproj.io/secret-type: cluster
    argocd-agent.argoproj-labs.io/agent-name: env61
type: Opaque
stringData:
  name: env61
  server: "https://argocd-agent-resource-proxy.argocd.svc:9090?agentName=env61"
  #   kubectl get secret -n addons internal-ca -o jsonpath='{.data.tls\.crt}'
  #   kubectl get secret -n argocd env61-client-tls -o jsonpath='{.data.tls\.crt}'
  #   kubectl get secret -n argocd env61-client-tls -o jsonpath='{.data.tls\.key}'
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "caData":   "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJjRENDQVJhZ0F3SUJBZ0lVWFNUeEU0NEx5RFcwVFlCMHF0WTJnS29UcXY0d0NnWUlLb1pJemowRUF3SXcKRmpFVU1CSUdBMVVFQXhNTGFXNTBaWEp1WVd3dFkyRXdIaGNOTWpZd05qQXpNVGcxTURJeVdoY05Nell3TlRNeApNVGcxTURJeVdqQVdNUlF3RWdZRFZRUURFd3RwYm5SbGNtNWhiQzFqWVRCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGNCt1c2F0Tm83VGVuZkxTMVoyZmwydGJMWlIrUWlSTzdhRGhKcHQvc29jenRMV0FnMUgKaHNTVGNYaHFuOHNXR1JDcWNnUkYwenp0clc4cmlLb201T1dqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lDcERBUApCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1c1WFVmSHQ4eXNVb1gzME1JNVNVazdYQ2s4REFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBMWtsYi9seUpNL2xPemNvWU5qS0lDRm1pa050OFlhb1VOZUg1d0xhSzgKa0FJaEFQa0tXWCttVEpOSS9uSlZtRnpsaEcrL2l5RFQrb1Nya3VPa0JoZlE3Zi8yCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K",
        "certData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJiVENDQVJTZ0F3SUJBZ0lVYnROcnMrdy9iWE5vNDhUL2hpZnA2cmxXM2Zvd0NnWUlLb1pJemowRUF3SXcKRmpFVU1CSUdBMVVFQXhNTGFXNTBaWEp1WVd3dFkyRXdIaGNOTWpZd05qRXpNRE13TnpFMFdoY05NamN3TmpFegpNRE13TnpFMFdqQVFNUTR3REFZRFZRUURFd1ZsYm5ZMk1UQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCR05VdEdDN0ZiRW1TeUxaTHdQaFlhbG5CRVhDbjZtQU5UUGQxVWQrT0w0KzlwZkdSYTcra1NRRk01QXgKY2lHVUxEYlJwazIyK2JoZSt0QzhaVXQ1Ni9LalJqQkVNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01DTUF3RwpBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGpCQmd3Rm9BVWx1VjFIeDdmTXJGS0Y5OURDT1VsSk8xd3BQQXdDZ1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnVXFJUXJBSUIyM3loQlhjdFUvV1Q4ZUo5YldiZ1dSeTVVMTkzeGZtRmkyMEMKSUFlUEpIMnpMcjBWZ01ndytwVjVBNVV0K3BJNzMrcnBEanRkWXoxT09wbjAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=",
        "keyData":  "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU9zenZSck9leTY0Szg2WUxHV3EzVVVML1BLTGNsMmpaR0phclhtNGl1MGZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWTFTMFlMc1ZzU1pMSXRrdkErRmhxV2NFUmNLZnFZQTFNOTNWUjM0NHZqNzJsOFpGcnY2UgpKQVV6a0RGeUlaUXNOdEdtVGJiNXVGNzYwTHhsUzNucjhnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
      }
    }
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: env61-node-alias
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  spiffeID: spiffe://stack.ai/cluster/env61/node
  parentID: spiffe://stack.ai/spire/server
  selectors:
    - azure_imds:subscription-id:c05b8dd7-5b0f-4be7-ba37-5f5a0eb52ca8
    - azure_imds:resource-group:mc_stackai-env61-rg_env61-aks_eastus
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: env61-argocd-agent-agent
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  spiffeID: spiffe://stack.ai/cluster/env61/ns/stackai-addons/sa/argocd-agent-agent
  parentID: spiffe://stack.ai/cluster/env61/node
  selectors:
    - k8s:ns:stackai-addons
    - k8s:sa:argocd-agent-agent
