apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: env64
  labels:
    app: mongodb-operator
    environment: env64
    argocd.argoproj.io/agent-id: env64
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
spec:
  destination:
    namespace: mongodb-operator
    name: env64
  project: default
  source:
    repoURL: https://mongodb.github.io/helm-charts
    chart: community-operator
    targetRevision: "0.12.0"
    helm:
      releaseName: mongodb-operator
      valuesObject:
        operator:
          watchNamespace: "*"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
