apiVersion: v1
kind: Namespace
metadata:
  name: env64
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: env64-client-tls
  namespace: argocd
spec:
  secretName: env64-client-tls
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: env64
  usages:
    - client auth
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
---
apiVersion: v1
kind: Secret
metadata:
  name: env64-cluster
  namespace: argocd
  annotations:
    argoproj.io/skip-reconcile: "true"
  labels:
    argocd.argoproj.io/secret-type: cluster
    argocd-agent.argoproj-labs.io/agent-name: env64
type: Opaque
stringData:
  name: env64
  server: "https://argocd-agent-resource-proxy.argocd.svc:9090?agentName=env64"
  #   kubectl get secret -n addons internal-ca -o jsonpath='{.data.tls\.crt}'
  #   kubectl get secret -n argocd env64-client-tls -o jsonpath='{.data.tls\.crt}'
  #   kubectl get secret -n argocd env64-client-tls -o jsonpath='{.data.tls\.key}'
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "caData":   "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJjRENDQVJhZ0F3SUJBZ0lVWFNUeEU0NEx5RFcwVFlCMHF0WTJnS29UcXY0d0NnWUlLb1pJemowRUF3SXcKRmpFVU1CSUdBMVVFQXhNTGFXNTBaWEp1WVd3dFkyRXdIaGNOTWpZd05qQXpNVGcxTURJeVdoY05Nell3TlRNeApNVGcxTURJeVdqQVdNUlF3RWdZRFZRUURFd3RwYm5SbGNtNWhiQzFqWVRCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGNCt1c2F0Tm83VGVuZkxTMVoyZmwydGJMWlIrUWlSTzdhRGhKcHQvc29jenRMV0FnMUgKaHNTVGNYaHFuOHNXR1JDcWNnUkYwenp0clc4cmlLb201T1dqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lDcERBUApCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU1c1WFVmSHQ4eXNVb1gzME1JNVNVazdYQ2s4REFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBMWtsYi9seUpNL2xPemNvWU5qS0lDRm1pa050OFlhb1VOZUg1d0xhSzgKa0FJaEFQa0tXWCttVEpOSS9uSlZtRnpsaEcrL2l5RFQrb1Nya3VPa0JoZlE3Zi8yCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K",
        "certData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJiakNDQVJTZ0F3SUJBZ0lVS21KejFNS05XQ1BjbFkrbVpQS2JaMTFMMVU0d0NnWUlLb1pJemowRUF3SXcKRmpFVU1CSUdBMVVFQXhNTGFXNTBaWEp1WVd3dFkyRXdIaGNOTWpZd05qRTBNVFV4TkRRNVdoY05NamN3TmpFMApNVFV4TkRRNVdqQVFNUTR3REFZRFZRUURFd1ZsYm5ZMk1qQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCT0hrOSsvSWZpWG5aUm5Yd3NkeTBkdFgzOGFBc2RLWFBIamZ3cG51S3NYcVNaaFMrSnF1UEc3clE5ZEQKa1poeDdxZmdWcHZ0M3BtdGk5Q1JOWXhCdm9HalJqQkVNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01DTUF3RwpBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGpCQmd3Rm9BVWx1VjFIeDdmTXJGS0Y5OURDT1VsSk8xd3BQQXdDZ1lJCktvWkl6ajBFQXdJRFNBQXdSUUlnTUpyYkhRTng2NWxHTjVYV1MxR21aSGhkOXp6ZXVEc3J4ZmtPRHhSZ095OEMKSVFEN2tYc1cxSTA0MnRrNi9KRnpzZDQ3Yjd2c25BWG1KOFJsTkRMa1dTZUU3Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K",
        "keyData":  "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNXUWNOQUltMGgzR2t5RUpGeVowZVVMQSt5aGNYMnQ4WlcwNWowQ0RJRXhvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNGVUMzc4aCtKZWRsR2RmQ3gzTFIyMWZmeG9DeDBwYzhlTi9DbWU0cXhlcEptRkw0bXE0OApidXREMTBPUm1ISHVwK0JXbSszZW1hMkwwSkUxakVHK2dRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
      }
    }
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: env64-node-alias
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  spiffeID: spiffe://stack.ai/cluster/env64/node
  parentID: spiffe://stack.ai/spire/server
  selectors:
    - azure_imds:subscription-id:c05b8dd7-5b0f-4be7-ba37-5f5a0eb52ca8
    - azure_imds:resource-group:mc_stackai-env64-rg_env64-aks_eastus
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: env64-argocd-agent-agent
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  spiffeID: spiffe://stack.ai/cluster/env64/ns/stackai-addons/sa/argocd-agent-agent
  parentID: spiffe://stack.ai/cluster/env64/node
  selectors:
    - k8s:ns:stackai-addons
    - k8s:sa:argocd-agent-agent
